### ISSUE TITLE
访问 'http://rate.tmall.com/list_detail_rate.htm'得不到评价数据？

### ISSUE THREAD

**Issue by hslxzdz** [Werneror/Practise#2]
```
url = 'http://rate.tmall.com/list_detail_rate.htm'
urlparams = {'itemId':str(itemId),'sellerId':str(sellerId),'currentPage':str(i)}
r = requests.get(url,params=urlparams,headers=headersParameters)
```
前辈，我在用浏览器访问‘http://rate.tmall.com/list_detail_rate.htm'可以得到json格式的所有评价数据，
但是在request里构造请求时只得到这样一串内容：
b'\r\n\r\n\r\n{"rgv587_flag": "sm", "url": "//rate.tmall.com:443/list_detail_rate.htm/_____tmd_____/punish?x5secdata=5e0c8e1365474455070961b803bd560607b52cabf5960afff39b64ce58073f7844a8dd94c89edef01763e7bda2153e72fcab45d62d62d1d0fb9af411e98157f55151e037d30b894fa1b9f0617640df860a901a36bd6d324642091753f1253ec47fad7705c7bf26a7ef1aa109e380a620a649c7f900a7c9e502b9d5614b21be76c585d510512f8be4cdb0d4e53b5804dcee26a90a7df58b61f4b6d8769304c257e0496fd369fe90d5a5cb0968745f36293173959473a52df991db9a057aa860e6ec7493fb62f9278e24f1101ec2a88496be64fe7c2b8f69454c3030f98912b20e57c906a34cd3389933259d1cdc60837267dab14593dfc4341433f7b16aa8ec901a66fc14f736ed45bc53517cde99db61ef652477ccb4bf7caafe10e57362d226cd6a27906d66221653de01d0c8621b7f55c9edda4450e5b8708806aa671a4bb3bcfb0c3aefac537538fb3c4518b2f3cc9bebe3999de89b715520fa7bf25efa24321bd982834025777f5d720b283432993f456a22bf2ab1f7cadbabe78d5bcac1c8747672219c71927eaae354887c77e001fce86cdaa9e9e50d6a8840aaf1539b42d6e3a3ddb9e15bb061459785a2b3abd84ada87e0d005666d68b20cea0d4894f2c53536e9489411b502b55c0f1e4c5a525b1a51e4ab381cd6589a57191a0d0c46662f2e043fac6bdb5b6990fa12f362185212ea6d4095c1d950656f095716aa6a7ceb02f25da156336197406ca10a517e4e20aa809bea00d717761a53df4306e3f286ae6f6898c4920396e71c09c9077057b2ae6d61c87a6cc6d32237eeff75d7a120df11d0c4875c33717cea47bf9c5d9a678964b11679bf2531504047e854&x5step=2"}'
这是怎么回事呢？

**Comment by Werneror** [comment]
我觉得有可能是登录状态的问题，在浏览器中访问时是在登录了tmall的状态下进行的。
还有可能是HTTP头部字段的问题。你可以分别抓包看看requests发出的请求和浏览器发出的请求有何差别，尽量模仿浏览器发出的请求。

**Comment by hslxzdz** [comment]
嗯，谢谢您，确实是因为没登录，在header里加上cookies，就能看到返回的评论了。
不过，获取cookie需要我手动在浏览器登录，然后把cookie复制下来粘贴过去。
事实上，我并不能用在代码中实现登录天猫，比如http://login.taobao.html，我用post方法发送账号和密码，结果报500。
是不是天猫反爬太厉害了呢？

**Comment by Werneror** [comment]
同样还是抓包看看requests发出的登录请求和浏览器发出的登录请求有何差别，若是做到requests发出的登录请求和浏览器发出的一模一样，便没有理由会报500错误。
以及现在登录淘宝不都要验证手机号码的吗？

**Comment by hslxzdz** [comment]
抓包工具是指像postman这样的吗。
访问评论页（http://rate.tmall.com/list_detail_rate.htm）这个我是照着
![image](https://user-images.githubusercontent.com/17683543/51224601-b1719f80-1981-11e9-8560-d2e3c42cdcae.png)
来模仿的，不过它需要保持登录状态。
就是模仿登录总失败。。。
![image](https://user-images.githubusercontent.com/17683543/51224518-47f19100-1981-11e9-9b46-92c87d2c9010.png)
我的headers都是照着写的，账号和密码也post过去了，结果就是报500.。。
我在我看网上说淘宝登录密码还要通过AES加密之后才能上传，直接传好像不可以，我们也不知道加密方法呀。

**Comment by Werneror** [comment]
抓包工具用什么都可以。写爬虫的话我感觉浏览器自带的抓包工具在大多数时候都是够用的。

模拟登录确实是爬虫的难点，尤其是像淘宝这样把登录搞得很复杂的网站。可以考虑试试selenium。

**Comment by hslxzdz** [comment]
嗯嗯，selenium我会用，谢谢您啦~
